server:
  port: 8082

spring:
  application:
    name: order-service-kafka
  kafka:
    topic:
      name: orderTopic
    producer:
      bootstrap-servers: localhost:9092 # Kafka broker address
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer